version: '3.8'

services:
  router1:
    build:
      context: .
      dockerfile: Dockerfile-router
    container_name: router1
    environment:
      - ROUTER_ID=router1
      - PORT=5000
    networks:
      rede:
        ipv4_address: 192.168.250.11

  router2:
    build:
      context: .
      dockerfile: Dockerfile-router
    container_name: router2
    environment:
      - ROUTER_ID=router2
      - PORT=5000
    networks:
      rede:
        ipv4_address: 192.168.250.12

  router3:
    build:
      context: .
      dockerfile: Dockerfile-router
    container_name: router3
    environment:
      - ROUTER_ID=router3
      - PORT=5000
    networks:
      rede:
        ipv4_address: 192.168.250.13

  router4:
    build:
      context: .
      dockerfile: Dockerfile-router
    container_name: router4
    environment:
      - ROUTER_ID=router4
      - PORT=5000
    networks:
      rede:
        ipv4_address: 192.168.250.14

  router5:
    build:
      context: .
      dockerfile: Dockerfile-router
    container_name: router5
    environment:
      - ROUTER_ID=router5
      - PORT=5000
    networks:
      rede:
        ipv4_address: 192.168.250.15

  host1:
    build:
      context: .
      dockerfile: Dockerfile-host
    container_name: host1
    command: ["python", "hosts.py", "host1", "192.168.250.11"]
    networks:
      rede:
        ipv4_address: 192.168.250.101

  host2:
    build:
      context: .
      dockerfile: Dockerfile-host
    container_name: host2
    command: ["python", "hosts.py", "host2", "192.168.250.12"]
    networks:
      rede:
        ipv4_address: 192.168.250.102

  host3:
    build:
      context: .
      dockerfile: Dockerfile-host
    container_name: host3
    command: ["python", "hosts.py", "host3", "192.168.250.13"]
    networks:
      rede:
        ipv4_address: 192.168.250.103

  host4:
    build:
      context: .
      dockerfile: Dockerfile-host
    container_name: host4
    command: ["python", "hosts.py", "host4", "192.168.250.14"]
    networks:
      rede:
        ipv4_address: 192.168.250.104

  host5:
    build:
      context: .
      dockerfile: Dockerfile-host
    container_name: host5
    command: ["python", "hosts.py", "host5", "192.168.250.15"]
    networks:
      rede:
        ipv4_address: 192.168.250.105

networks:
  rede:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.250.0/24
