FROM python:3.10-slim

# Instala ping e ferramentas de rede
RUN apt-get update && \
    apt-get install -y iputils-ping iproute2 curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY client.py .

CMD ["tail", "-f", "/dev/null"]
